; platformio.ini  (solucionario/ and starter_kit_estudiante/ are byte-identical)
[platformio]
src_dir = .
include_dir = .
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    https://github.com/FluxGarage/RoboEyes.git
build_flags =
    -DCORE_DEBUG_LEVEL=0
